config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    
    has_many :tasks 

    validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :correct_user, only: [:edit, :update]

    def index 
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
    end

    def new
        # @category = Category.new
        @category = current_user.categories.build
    end

    def create
        # @category = Category.create(category_params)
        @category = current_user.categories.build(category_params)

        if @category.save
            redirect_to @category
        else
            render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to @category
        else
            render :edit
        end
    end

    def correct_user
        @category = current_user.categories.find_by(id: params[:id])
        redirect_to categories_path, notice: "Not authorized to edit this category."  if @category.nil?
    end

    private

    def category_params
        params.require(:category).permit(:title, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = current_user.categories.tasks.build
  end

  # GET /tasks/1/edit
  def edit
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
  end

  # POST /tasks or /tasks.json
  def create
    @category = current_user.categories.find(params[:category_id])
    @task = @category.tasks.create(task_params)
    redirect_to category_path(@category)
    
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    if @task.update(task_params)
      redirect_to @category
    else render :edit
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @category = current_user.categories.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
    @task.destroy
    redirect_to category_path(@category)
  end

  def correct_user
    @category = current_user.categories.find(params[:category_id])
    redirect_to categories_path, notice: "Not authorized to perform this action."  if @category.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:header, :description, :category_id, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/create.html.erb
<h1><%= @category.title %></h1>

app/views/categories/edit.html.erb
<%= form_with model: @category, method: :patch do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
    <% @category.errors.full_messages_for(:title).each do |message| %>
      <div class="form-text form-text-validation"><%= message %></div>
    <% end %>
  <%= form.submit 'Update Category' %>
<% end %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <% if category.user == current_user %>
    <div class="col-sm-4 d-flex text-center justify-content-center">
      <div class="card mb-4">
        <div class="card-body d-flex flex-column align-items-center justify-content-between">
          <h4 class="card-title"><strong><%= category.title %></strong></h4>
          <h2>This is <%= category.user_id %>'s task</h2>
          <%= link_to "View tasks for this category", category %>
        </div>
       </div>
    </div>
  <% end %>
<% end %>

app/views/categories/new.html.erb
<%= form_with model: @category do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <div>
    <% @category.errors.full_messages_for(:title).each do |message| %>
      <div class="form-text form-text-validation"><%= message %></div>
    <% end %>
    </div>
    <%= f.number_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden %>
  </div>
  <%= f.submit 'Create Category' %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<%= link_to "Edit Category", edit_category_path(@category) %>

<%= render @category.tasks %>

<h2>Add a task:</h2>
<%= render 'tasks/form' %>

<%= link_to "View all categories", root_path %>





app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journalapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">to do list by e-vion</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All Categories", categories_path, class: "nav-link" %>
          <%# <a class="nav-link active" aria-current="page" href="#">All Categories</a> %>
        </li>



        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Create Category!", new_category_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

    <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ @category, @category.tasks.build ] do |form| %>
  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
      <%= form.label :deadline %>
      <%= form.datetime_field :deadline, min: Date.today %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<h5><%= task.header %></h5>
<p><%= task.description %></primary>
<p>Due on: <%= task.deadline %></primary>


<%# <button type="button" class="btn btn-primary"></button> %>
<%= link_to "Edit Task", edit_category_task_path(@category) %>

<%= link_to "Delete Task", [task.category, task],
                  method: :delete %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

    <%= render 'form', task: @task %>
    <%= link_to 'Back', category_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Header</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.header %></td>
        <td><%= task.description %></td>
        <td><%= task.category_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }</td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Header:</strong>
  <%= @task.header %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category_id %>
</p>

<%= link_to 'Back', tasks_path %>